### ISSUE TITLE
function prototypes don't have `restrict` keyword despite AC_C_RESTRICT.

### ISSUE THREAD

**Issue by jeremyhannon** [rurban/safeclib#1]
I'm just curious why the library function prototypes don't use the `restrict` keyword per the C11 Annex K library. I see in the `configure.ac` file that you're using `AC_C_RESTRICT` which gnu [defines ](https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/C-Compiler.html)as:

> If the C compiler recognizes the restrict keyword, don't do anything. If it recognizes only a variant spelling (__restrict, __restrict__, or _Restrict), then define restrict to that. Otherwise, define restrict to be empty. Thus, programs may simply use restrict as if every C compiler supported it; for those that do not, the makefile or configuration header defines it away.

So I assume there's no harm in inserting the `restrict` keyword for all of the `char *` pointers per the standard since it would either be removed or matched each compiler's keyword. I can make this change if you want.

**Comment by rurban** [comment]
Yes, that would be great indeed. Thanks.

**Comment by rurban** [comment]
Thanks for the implementation. Released with 2.0
