### ISSUE TITLE
error: ‘-fstack-protector’ not supported for this target

### ISSUE THREAD

**Issue by kilobyte** [rurban/safeclib#100]
Hi!  I'm afraid that adding `-fstack-protector` unconditionally doesn't work: it's not supported on at [least](https://buildd.debian.org/status/fetch.php?pkg=safeclib&arch=alpha&ver=3.6-1&stamp=1633844459&raw=0) [some](https://buildd.debian.org/status/fetch.php?pkg=safeclib&arch=hppa&ver=3.6-1&stamp=1633692369&raw=0) [archs](https://buildd.debian.org/status/fetch.php?pkg=safeclib&arch=ia64&ver=3.6-1&stamp=1634100304&raw=0).

Thus, could you please wrap this setting in a configure check?

**Comment by rurban** [comment]
I compiled successfully on hppa, with a debian:buster for hppa.
The problem seems to be your /usr/share/dpkg/pie-compile.specs, which adds -fstack-protector to the already existing -fstack-protector-strong.

**Comment by kilobyte** [comment]
I found what's wrong:
```
checking whether C compiler accepts -Werror=unknown-warning-option... (cached) no
checking whether C compiler accepts -fstack-protector-strong... yes
checking whether C compiler accepts -fstack-clash-protection... yes
checking whether C compiler accepts -fcf-protection... no
checking whether the linker accepts -fstack-protector-strong... yes
checking whether the linker accepts -fstack-clash-protection... yes
checking whether the linker accepts -fcf-protection... no
```
The check in `AX_APPEND_COMPILE_FLAGS` ignores warnings, thus you'd need to give it `-Werror`.

There's no `-Wunknown-warning-option` on gcc, and even if it did exist, it would affect only unknown `-W` options, while this is a `-f` that's known but unimplemented.  And there appears to be no tag that would allow a specific `-Werror=something` :(

**Comment by rurban** [comment]
Use --disable-hardening

**Comment by kilobyte** [comment]
This helped on all relevant archs (alpha hppa ia64), thanks!
