### ISSUE TITLE
Constraint handler trips on `%Lf` for `printf_s`

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [rurban/safeclib#103]
**Expected Behaviour:** `%Lf` acts as a format specifier for `long double`

**Actual Behaviour:** A constraint handler is tripped

**Example:**
The following:
```
printf_s("%Lf\n", 0.0L);
```
Trips a constraint handler for `printf_s: illegal %L format-specifier`.

The same goes for all format specifiers allowing the `L` prefix - `fF eE aA gG`

I can work around not having `long double` but it does feel like this was just missed? It is a bit of a weird one in fairness.

It is listed on cppreference on the leftmost part of the `printf`-family format specifier table here: https://en.cppreference.com/w/c/io/fprintf but it's possible this is erroneous?

Thanks!

**Comment by rurban** [comment]
Thanks. I forgot to test all the new cases. This is the new implementation, right?

**Comment by Th3T3chn0G1t** [comment]
Its trunk so I presume so? I have this submoduled so I try to keep it at latest

**Comment by rurban** [comment]
Good, that's what I thought. I have now a complete new printf Implementation, which misses a lot of test cases, and obviously many %L format. I just added %Ls and %Lc, the others are also missing
