### ISSUE TITLE
When to build Safe Linux Kernel Module vs Userspace library ?

### ISSUE THREAD

**Issue by ShadyAbuKalam** [rurban/safeclib#104]
I am a bit lost here. There are two outputs of the building process, a kernel module and userspace lib (.a or .so).
I am not sure if I need both to integrate the lib into my codebase ? 
Would you clarify more, when to use what ?

Thanks

**Comment by rurban** [comment]
It's obvious. The kernel module is needed if you build a patched kernel with it. Haven't seen that patch though.

The rest is for userspace.
