### ISSUE TITLE
%n constraint in formatting functions

### ISSUE THREAD

**Issue by Nishank-25** [rurban/safeclib#105]
As stated in **_C11 standard (ISO/IEC 9899:2011): K.3.5.3.3 The printf_s function (p: 593-594)_**

>The %n specifier394) (modified or not by flags, field width, or precision) shall not appear in the string pointed to by format.

But I don't see the handling of  flags.

**Comment by rurban** [comment]
It is handled now here. https://github.com/rurban/safeclib/blob/97e5923e56109b963a1fb6a6babf1875752fe197/src/str/vsnprintf_s.c#L1054

before it was also handled.
