### ISSUE TITLE
Test failures in test suite with 3.7-pre on macOS Big Sur with Apple clang version 11.0.0 (clang-1100.0.33.17) — no wget

### ISSUE THREAD

**Issue by jleffler** [rurban/safeclib#112]
(See issue 111 for compiler warnings — this is the same environment, and the failing tests are not associated with the code that had warnings.)

I just downloaded safeclib 3.7-pre. Running 'make check' on macOS Big Sur (11.6.3) after an apparently problem-free build, I get three test failures):

…

  CC       test_qsort_s.o
  CCLD     t_qsort_s
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: t_memcpy_s
PASS: t_memmove_s
PASS: t_memset_s
PASS: t_sprintf_s

…

PASS: t_wcscoll_s
PASS: t_wcslwr_s
PASS: t_wcsupr_s
FAIL: t_towfc_s
../build-aux/test-driver: line 107: 96189 Segmentation fault: 11  "$@" > $log_file 2>&1
FAIL: t_towlower
../build-aux/test-driver: line 107: 96209 Segmentation fault: 11  "$@" > $log_file 2>&1
FAIL: t_towupper
PASS: t_wcsfc_s
PASS: t_wcsnorm_s
PASS: t_memcpy32_s
PASS: t_memcpy16_s

…

PASS: t_bsearch_s
PASS: t_qsort_s
\============================================================================
Testsuite summary for Safe C Library 3.7
\============================================================================
\# TOTAL: 126
\# PASS:  123
\# SKIP:  0
\# XFAIL: 0
\# FAIL:  3
\# XPASS: 0
\# ERROR: 0
\============================================================================
See tests/test-suite.log
Please report to https://github.com/rurban/safeclib/issues
\============================================================================
make[4]: *** [test-suite.log] Error 1

Looking in the tests/test-suite.log, I find:

FAIL: t_towfc_s
\===============

downloading CaseFolding.txt ...sh: wget: command not found
 done
FAIL t_towfc_s (exit status: 1)

FAIL: t_towlower
\================

downloading CaseFolding.txt ...sh: wget: command not found
FAIL t_towlower (exit status: 139)

FAIL: t_towupper
\================

downloading DerivedGeneralCategory.txt ...sh: wget: command not found
 done
downloading CaseFolding.txt ...sh: wget: command not found
FAIL t_towupper (exit status: 139)

This is a new, essentially "as supplied by Apple" installation of macOS Big Sur.  So, on a Mac, it is not guaranteed that there will be a copy of `wget`.  I'm not sure that a "segmentation fault" is an appropriate way to handle "no wget found".

**Comment by rurban** [comment]
Yes, I need to change that. Either ship the files again, or skip the tests.

Thanks for testing!

Jonathan Leffler ***@***.***> schrieb am Fr., 28. Jan. 2022,
22:36:
