### ISSUE TITLE
build fail on powerpc: uint64

### ISSUE THREAD

**Issue by kilobyte** [rurban/safeclib#113]
32-bit powerpc fails with:
```
perf_private.h:109:15: error: ‘uint64’ undeclared (first use in this function); did you mean ‘uint64_t’?
```
[Full log](https://buildd.debian.org/status/fetch.php?pkg=safeclib&arch=powerpc&ver=3.7-1&stamp=1643490763&raw=0).

**Comment by rurban** [comment]
Fixed with v3.7.1
