### ISSUE TITLE
single header file?

### ISSUE THREAD

**Issue by laoshaw** [rurban/safeclib#114]
can we have a single header file to include them all?

it seems to have them all we need do:

```
#include <safeclib/safe_lib.h>
#include <safeclib/safe_mem_lib.h>
#include <safeclib/safe_str_lib.h>
```

it would be nice to have a manpage for safeclib_overview that also simply mention how it is supposed to be used(e.g header files) and libraries, so it's beginner friendlier.

**Comment by rurban** [comment]
PR welcome
