### ISSUE TITLE
Arm64 compilation has incorrect assembly instructions

### ISSUE THREAD

**Issue by dcblack** [rurban/safeclib#116]
In order to compile this library under macOS 12.3.1 on Apple Silicon M1, I had to do two things:
1. ./configure --disable-hardening ;# I need to investigate further
2. Changed src/mem/mem_primitives_lib.h to use correct assembly instructions. On aarch64, the dmb, isb, and dsb instructions require an argument. The strongest form uses 'sy'. Thus '**dmb s**y'. Below is a diff. I am a bit puzzled as to why you use both '**dmb**' and '**dsb**' since 'dsb' covers the same ground (I teach Armv8 architecture). See <https://stackoverflow.com/questions/23105052/is-there-a-need-for-dmb-if-we-are-using-dsb> for instance. If you have a good reason for its use, please elaborate. I believe it just adds an instruction that unnecessarily slows the code.

The basic action for this issue would be to remove the 'dmb' and add the 'sy' argument to each of the remaining two instructions'.

❯ git diff
```
diff --git a/src/mem/mem_primitives_lib.h b/src/mem/mem_primitives_lib.h
index 72365e4e..f0594fc7 100644
--- a/src/mem/mem_primitives_lib.h
+++ b/src/mem/mem_primitives_lib.h
@@ -144,7 +144,7 @@
 #elif defined(__GNUC__) && defined(ASM_INLINE) && defined(__i386__)
 #define MEMORY_BARRIER ASM_VOLATILE("lock; addl $0,0(%%esp)" ::: "memory")
 #elif defined(ASM_INLINE) && (defined(HAVE_ARM_NEON) || defined(HAVE_ARM_NEON))
-#define MEMORY_BARRIER ASM_VOLATILE("dmb; dsb; isb" ::: "memory")
+#define MEMORY_BARRIER ASM_VOLATILE("dmb sy; dsb sy; isb sy" ::: "memory")
 #elif (defined(__GNUC__) && __GNUC__ >= 4) || defined(HAVE___SYNC_SYNCHRONIZE)
 #define MEMORY_BARRIER __sync_synchronize()
 /* new gcc-5 memory_barrier insn for most archs:
```

**Comment by rurban** [comment]
Can you check?

**Comment by dcblack** [comment]
I do use this library with Arm64 on macOS (Apple Silicon M1 Max). I use the cmake installation process and had to add -DCMAKE_APPLE_SILICON_PROCESSOR=`uname -m` to get it to compile.

**Comment by rurban** [comment]
Ok, I've merged it
