### ISSUE TITLE
Setting sl_default_handler to abort_handler_s before runtime

### ISSUE THREAD

**Issue by James-Silva** [rurban/safeclib#122]
Hi,
Is there a way to specify `sl_default_handler = abort_handler_s` during configure or compile time? I can set it fine from a main function:
`
int main() // compiles OK
{
	set_str_constraint_handler_s(abort_handler_s);
	set_mem_constraint_handler_s(abort_handler_s);
}
`
but am working on a project that has many (100+) executables with their own main functions that I would like to link to with this library and would rather not add these lines to each one.

I suspect that there might be a configure option for it, but I did not see any when running `./configure --help`. I tried calling `#define sl_default_handler abort_handler_s` (kind of hacky I know) after including the libraries headers, but did not have much luck with that either.
Thanks!

**Comment by rurban** [comment]
Not that I'm aware of, but a configure patch would be welcome

**Comment by James-Silva** [comment]
I might! But since I won't be able to do it right away, I'll close the issue. Thanks

**Comment by rurban** [comment]
Done

**Comment by James-Silva** [comment]
Awesome! :)
