### ISSUE TITLE
fprintf_s printing NULL characters to file

### ISSUE THREAD

**Issue by ajmunro** [rurban/safeclib#124]
Hi, 

When using fprintf_s, it appears that it is printing the NULL character for the string termination to the file.
This can be demonstrated using the following code:

```
#include "include/safec.h"

int main(int argc, char** argv) {

    char* outputFilename = "fprintf_s_test.txt";
    FILE* fd = fopen(outputFilename, "w");

    fprintf_s(fd, "Print string to file");

    return 0;
}
```

The resulting file then looks like:

`Print string to file^@`

Is this intentional? This does differ from the implementation of fprintf. 
The line of code which appears to do this is: https://github.com/rurban/safeclib/blame/master/src/str/vsnprintf_s.c#L1080
If we remove this line, the issue no longer occurs, and as far as I can tell has no bad effects

**Comment by rurban** [comment]
It's a bug, and it certainly misses a testcase also. embarrassing

**Comment by ajmunro** [comment]
Thanks for the quick response!
