### ISSUE TITLE
getenv_s problems with NULL terminator?

### ISSUE THREAD

**Issue by aidan-copeland** [rurban/safeclib#128]
The usage examples of getenv_s at https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/getenv-s-wgetenv-s?view=msvc-170 show it being called twice: once to find the length of the environment variable, and a second time to fill in that environment variable:

```
   getenv_s( &requiredSize, NULL, 0, "LIB");

   libvar = (char*) realloc(libvar, requiredSize * sizeof(char));
   if (!libvar)
   {
      printf("Failed to allocate memory!\n");
      exit(1);
   }

   // Get the new value of the LIB environment variable.
   getenv_s( &requiredSize, libvar, requiredSize, "LIB" );
```

In the implementation, the length is determined by strlen(buf).  This does not include space for the NULL terminator.  

There are two problems here.  
Based on example usage, a user will set the value of dmax to be the length returned by this function when called the first time.  This fails the test
```
    if (unlikely(dmax != 0 && len1 >= dmax)) {
```
because len1 == dmax.

Secondly, strcpy_s will miss the final byte of the environment variable being copied, because it only copies the number of bytes in the environment variable, not the NULL terminator.

I think the fix is to set
```
            *len = len1 + 1;
```
when returning a value for the length, including space for the NULL terminator.

**Comment by rurban** [comment]
Ok, so how about returning the size on windows, and the length on standard-conforming platforms?
