### ISSUE TITLE
Is it "safe" to have large values of RSIZE_MAX_MEM?

### ISSUE THREAD

**Issue by cronhan** [rurban/safeclib#132]
Sorry if this is an inappropriate question, but I only came across the problem after not understanding why my code kept failing.
I am trying to use `memcpy_s` with large (just shy of 2GB) data, but by default `RSIZE_MAX_MEM` is defined as 256MB.
My question is, is it okay to compile the library with a much larger limit (say thumbsuck 128GB, or even more to "future proof" the code), or will it break in other subtle ways? I should add that I exclusively use 64-bit Linux and don't require other platforms. Is it better to call `memcpy_s` iteratively in this case? Does the "native" `memcpy_s` of Windows have similar limits, because my current examples all run fine on there.
Input is much appreciated!

**Comment by rurban** [comment]
2GB is not really safe, but it depends on your system. 
On large systems it would be perfectly fine, but in 99% of such cases its an overflow or DOS attack.
Why cannot you use memcpy() there? this would use the much more efficient mmap remapping trick.

of course you can set your RSIZE_MAX_MEM to a much larger value, nothing will break. I have no idea of the RSIZE_MAX_MEM value with the native Windows memcpy_s.

**Comment by cronhan** [comment]
Okay, thanks for the feedback!
