### ISSUE TITLE
Release 3.8.0?

### ISSUE THREAD

**Issue by mattsheerin** [rurban/safeclib#134]
The ChangeLog mentions a 3.8.0 after 3.7.1, last updated in September 2022, but the most recent release was actually 3.7.1 in February of that year. There's at least one bug in the latest release causing problems with us trying to use safe C functions (https://github.com/rurban/safeclib/issues/124), which was fixed but never released.

Can we get a new release please?

**Comment by rurban** [comment]
oh, maybe I forgot about that. will see this week
