### ISSUE TITLE
eliminate inclusion loops in safe_mem_lib.h and safe_str_lib.h

### ISSUE THREAD

**Issue by jeremyhannon** [rurban/safeclib#14]
I'm concerned that there are inclusion loops. Specifically, safe_mem_lib.h and safe_str_lib.h both include safe_lib.h which then includes both of them. I assume this is because safe_lib.h defines rsize_t and the abort/ignore handlers. I would suggest that rsize_t be moved into safe_types.h and maybe the handlers need to be put in their own .c/.h files. That way, safe_mem_lib.h and safe_str_lib.h can include safe_types.h and the safe_handlers.h but that's it. Then safe_lib.h will include safe_str_lib.h and safe_mem_lib.h.

Any issue with that restructuring to eliminate inclusion loops?

**Comment by rurban** [comment]
sounds good. c++ is also a good check for finding such recursion errors.

**Comment by Juno-Explorer** [comment]
👍🏻

**Comment by rurban** [comment]
Note that I had to change the includes a bit for windows support.
Currently I'm fine with safe_lib.h being included by the 2 others.
Just doxygen needs to get 2 more cpp defines to stop worrying.

**Comment by rurban** [comment]
Done with 234f3b0bf2400303d7dd369e1d97a853e0178c23

**Comment by jeremyhannon** [comment]
234f3b0 doesn't get rid of the inclusion loops. `safe_str_lib.h` still includes `safe_lib.h`. The fix I envision is to remove all types from safe_lib.h so that safe_str_lib.h doesn't need to depend on it at all.

**Comment by rurban** [comment]
Fixed with fb4a6d587777298522ecbddfac20328ac50894cd
