### ISSUE TITLE
Misleading @return documentation on errno_t

### ISSUE THREAD

**Issue by mschulz-at-hilscher** [rurban/safeclib#141]
Reading the documentation, we realized that some parts are misleading. For example, in the strcmp_s function (https://github.com/rurban/safeclib/blob/master/src/extstr/strcmp_s.c#L61) it is not clear that the first three values are returned via resultp. Instead it looks like, the first three values are returned as return values:
![grafik](https://github.com/user-attachments/assets/b774664e-a065-4354-a3e2-511b192b351e)

It would be better to clearly state which values are returned via parameter and which as actual return value of the function.

**Comment by rurban** [comment]
I don't get it. This is the doc, which is very clear, and not misleading.

```
 * @param[in]   dest       pointer to string to compare against
 * @param[in]   dmax       restricted maximum length of string dest
 * @param[in]   src        pointer to the string to be compared to dest
 * @param[out]  resultp    pointer to int result, greater than 0,
 *                         equal to 0 or less than 0, if the string pointed
 *                         to by dest is greater than, equal to or less
 *                         than the string pointed to by src respectively.
 *
 * @pre   Neither dest, src nor resultp shall be a null pointer.
 * @pre   dmax shall not be 0
 * @pre   dmax shall not be greater than RSIZE_MAX_STR and size of dest
 *
 * @return  resultp (when the return code is OK)
 * @retval  >0         when dest greater than src
 * @retval   0         when strings the same
 * @retval  <0         when dest less than src
 * @retval  EOK        when comparison is complete
 * @retval  ESUNTERM   when src is unterminated
 * @retval  ESNULLP    when dest/src/resultp is NULL pointer
 * @retval  ESZEROL    when dmax = 0
 * @retval  ESLEMAX    when dmax > RSIZE_MAX_STR
 * @retval  EOVERFLOW  when dmax > size of dest (optionally, when the compiler
 *                     knows the object_size statically)
 * @retval  ESLEWRNG   when dmax != sizeof(dest) and --enable-error-dmax
 *
```

It's totally clear that there is only one out parameter, resultp. With some possible result values.
What exactly should be improved?

**Comment by rurban** [comment]
Ah, now I understand. It's this dilemma: https://stackoverflow.com/questions/7730409/difference-between-paramout-and-return-in-doxygen
