### ISSUE TITLE
run configure not in the rootdir --enable-strmax --enable-memmax doesn't work

### ISSUE THREAD

**Issue by YohnWang** [rurban/safeclib#143]
Hello
When I build this lib, I make a dir `build` in the source rootdir, and then `cd build && ../configure --prefix=$PWD/install --enable-strmax=$MAX_SIZE --enable-memmax=$MAX_SIZE`
the header `safe_config.h` generate in `build`, and RSIZE_MAX_STR is set $MAX_SIZE
after install, I write a test
```
#include<safec.h>
#include<stdio.h>
char s[10*1024] = {[0 ... 10*1024-1] = 'a'};
int main()
{
	printf("%zd\n", strnlen_s(s, sizeof(s)));
}
```
the program print `0`
And then I use `./configure --prefix=$PWD/install --enable-strmax=$MAX_SIZE --enable-memmax=$MAX_SIZE`
it works

Is this a build bug?
It seems like lib sources always use  `safe_config.h` which in `include/` not `build/include`

**Comment by rurban** [comment]
This would require a `make distclean` to clean out the previous build artefacts.
We dont support using both in-tree and out-of-tree builds together. Nobody does this.
