### ISSUE TITLE
don't use inclusion guards when including header files

### ISSUE THREAD

**Issue by jeremyhannon** [rurban/safeclib#20]
inclusion guards (sentinels) should not be used outside of the header in which they are defined. And I think it's alright/good/expected that a header file could be `#include`d multiple times in a chain of headers. That's why we have inclusion guards inside every header file to prevent actual multiple inclusion of the header contents. So I don't think the library should include code like the following.

```
#ifndef __SAFE_LIB_H__
  #include "safe_lib.h"
#endif
```

It should simply be `#include "safe_lib.h"` Inside the header file we already have:

```
#ifndef __SAFE_LIB_H__
#define __SAFE_LIB_H__
... file contents
#endif /* __SAFE_LIB_H__ */
```

Are you receiving a warning somewhere when you write the code like this? Maybe a warning that needs to be tuned/silenced?

**Comment by rurban** [comment]
Ah, that's right.
I was playing with mingw support that time, which needed it, and obviosuly wrapped my head 360˚.

Needs to be fixed, as you suggested.
