### ISSUE TITLE
`#define RCNEGATE(x)  (-x)` for non-kernel usage?

### ISSUE THREAD

**Issue by jeremyhannon** [rurban/safeclib#23]
For many/most of the functions, the C11AnnexK standard says that a negative value should be returned if there is a runtime constraint violation. However, it appears the safeclib functions are returning positive numbers if they're not being compiled for `__KERNEL__`. In every safeclib function the error return values are [wrapped as `RCNEGATE(x)`](https://github.com/rurban/safeclib/blob/master/src/str/snprintf_s.c#L102) and in `safeclib_private.h` the macro is [`#define RCNEGATE(x)  (x)`](https://github.com/rurban/safeclib/blob/master/src/safeclib_private.h#L133) when `__KERNEL__` is not defined.

So maybe you all can help me with some historical perspective. Is there an OS/platform that only accepts unsigned return values for error codes? Under what scenarios should the error values not be negative? The C11 Annex K functions are defined with `int` as the return type, so I would assume the negative version should always be returned.

**Comment by rurban** [comment]
That was a decision by Cisco. I'll ask them

**Comment by rurban** [comment]
I'll act according to the documentation.
So the printf family needs to return negative error numbers. Fixed that with 4e7cc244cc9ad9119f1a9a0f1e268db4bede83d1

**Comment by rurban** [comment]
The other str*_s functions which do return errno_t definitely return positive errnum's.
The return type errno_t also suggests returning a positive errno as with most other errno's.

E.g. MSVC strcpy_s returns either EINVAL for our ESNULLP or ERANGE for our ESNOSPC.
So I think we are now done with that.

**Comment by jeremyhannon** [comment]
:+1: Ok so for functions with `errno_t` return type, return a positive error number. For functions with `int` return type, return a negative number.
