### ISSUE TITLE
sprintf non-'n' functions should return zero when runtime constraint violation

### ISSUE THREAD

**Issue by jeremyhannon** [rurban/safeclib#24]
We’ve noticed there’s a difference in the [C11AnnexK standard](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf) between the error return values for ‘n’ and non-n versions of the sprintf functions, but the safeclib implementations don’t make this distinction.

For **`sprintf`**:

> **Returns**
> If no runtime-constraint violation occurred, the `sprintf_s` function returns the number
> of characters written in the array, not counting the terminating null character. If an
> encoding error occurred, `sprintf_s` returns a negative value. **If any other runtime constraint
> violation occurred, `sprintf_s` returns zero.**

For **`snprintf`**:

> **Returns**
> The `snprintf_s` function returns the number of characters that would have been
> written had n been sufficiently large, not counting the terminating null character, or a
> **negative value if a runtime-constraint violation occurred**. Thus, the null-terminated
> output has been completely written if and only if the returned value is nonnegative and
> less than n.

Note that for the ‘n’ versions, a negative value is returned for runtime constraint violations, whereas the non-n versions return zero. This difference doesn’t really make sense to us, but we found a [2005 document](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1141.pdf) explaining at least the need for the non-'n' versions to return a negative value for encoding errors instead of always returning zero as in the older C standard.

We notice that all of the ‘printf’ implementations in safeclib use [`RCNEGATE()`](https://github.com/rurban/safeclib/blob/master/src/str/sprintf_s.c#L93) to return an error code, which [never maps to zero](https://github.com/rurban/safeclib/blob/master/src/safeclib_private.h#L133), so the non-n versions aren’t following the spec because they’re not returning zero. So if everyone’s ok with it, we’ll submit a PR to clarify the runtime constraint error values returned by the sprintf family of functions per the standard. We have proposed a [separate issue](https://github.com/rurban/safeclib/issues/23) to ask why error values are being returned as positive numbers instead of negative numbers.

Although safe_lib_errno_.h already has `#define EOK ( 0 )`, I assume we'll have to overload zero and define another symbol like `#define SPRINTF_CONS_VIOL ( 0 )` so at least when someone reads the code they can see the what type of error we're returning.

found by @Juno-Explorer

**Comment by jeremyhannon** [comment]
BTW, here's my notes about what the return values are under both error conditions per the C11 standard:

  | encoding | runtime violation
-- | -- | --
sprintf |   | negative
snprintf |   | negative
vsprintf | negative | (assumed negative)
vsnprintf |   | negative
swprintf | negative | negative
vswprintf |   | EOF macro
sprintf_s | negative | zero
snprintf_s |   | negative
vsprintf_s | negative | zero
vsnprintf_s |   | negative
swprintf_s | negative | zero
vswprintf_s | negative | zero

**Comment by rurban** [comment]
Yes, I already fixed the documentation, but was confused about RCNEGATE (kernel vs non-kernel).
But I don't like the name `SPRINTF_CONS_VIOL`

**Comment by rurban** [comment]
Fixed with 00b2c96dcc1f32e5384a21c18f8b158ad8e3db3f
