### ISSUE TITLE
memory functions: smax=0 should be valid

### ISSUE THREAD

**Issue by jeremyhannon** [rurban/safeclib#27]
I see that all of the memory operations (`memcpy_s`, `memmove_s`, `memset_s`) check if `smax == 0` and if so then handle it as a constraint violation. However, I can't find that requirement in the C11AnnexK standard. I agree, it's stupid for a user to request copying zero bytes but I think it's still a valid operation that should have a return value of `EOK` (zero) instead of `ESZEROL`. Please let me know if I missed something in the standard. A side benefit of removing this check would be a slight performance improvement in the normal non-zero case.

FYI @Juno-Explorer

**Comment by rurban** [comment]
I don't care that much about the perf. issue, but about convenience and conformance, analog to `free(NULL)`. 
I'll check how prior art (MSVC) does it, when the standard does not mention it.

**Comment by rurban** [comment]
In MSVC smax=0 is valid: https://msdn.microsoft.com/en-us/library/wes2t00f.aspx

**Comment by rurban** [comment]
memset_s documents the different behavior if under C11: Since C11 smax=0 is allowed, before it fails with ESZEROL. So we'll have to check the features.

**Comment by jeremyhannon** [comment]
fixed in d4539981f7e359569627064756b046206f1f4886.

**Comment by jeremyhannon** [comment]
@rurban since you now have a `HAVE_C11` and `WANT_C11` I was a little confused about the difference. So I'd suggest renaming `WANT_C11` to `WANT_C11_ANNEXK` or `WANT_C11_LIB_EXT1` to make it clearer that you're wanting a subset/extension instead of wanting to use the C11 base standard.

**Comment by rurban** [comment]
I admit it's confusing at the first glance.
But I'd rather stay with the short form. It's only used in a few places where the actual upstream code is usable (`memset_s` on darwin).

`WANT_C11` means `#if __STDC_WANT_LIB_EXT1__ >= 1`, yes. But we would need to use the long form `#if defined(__STDC_WANT_LIB_EXT1__) && (__STDC_WANT_LIB_EXT1__ >= 1)`

The idea of safec is to implement C11 fully. Other's say they do, but they don't. Having this discrepancy, I think it's easier to make it clear with this short name. 
I don't want to emphasis it as extension, safe functions must be the default. Microsoft even warns all users to switch over to the safe variants.
