### ISSUE TITLE
memcpy_s: clear destination buff if (smax > RSIZE_MAX_MEM) but dst and dstMax are valid.

### ISSUE THREAD

**Issue by jeremyhannon** [rurban/safeclib#28]
I think I found a bug. From memcpy_s description in the standard:

> If there is a runtime-constraint violation, the memcpy_s function stores zeros in the first
> s1max characters of the object pointed to by s1 if s1 is not a null pointer and s1max is
> not greater than RSIZE_MAX.

But in the current [memcpy_s](https://github.com/rurban/safeclib/blob/master/src/mem/memcpy_s.c#L99), the destination buffer is not set to zeros even if both the dst and dstMax are valid. This will require splitting apart these two max comparisons.

I haven't checked other functions for the same failure.

**Comment by rurban** [comment]
You mean when `dmax < RSIZE_MAX_MEM && smax > RSIZE_MAX_MEM`?

**Comment by jeremyhannon** [comment]
correct, that conditional should be split.

**Comment by jeremyhannon** [comment]
:+1:
