### ISSUE TITLE
Validation over dmax should be (dmax<= 0) instead of (dmax== 0)

### ISSUE THREAD

**Issue by Juno-Explorer** [rurban/safeclib#29]
The validation check which we are having for checking the destination size equal to zero should be updated to less than equal to zero for more robustness. 
As standard claims that destination size should not be equal zero (which has implicit meaning that it shouldn't be less than zero too).

**Comment by rurban** [comment]
Nope, that would be hardly correct. ESZEROL is for zero and zero only.

dmax is rsize_t, which is size_t, which is unsigned long. So there's no dmax<0, only overflow, which is caught by ESLEMAX
