### ISSUE TITLE
Doxygen tags for function header comments

### ISSUE THREAD

**Issue by jeremyhannon** [rurban/safeclib#3]
We're using doxygen for auto-generating documentation and the safeclib C file comments already use `/**` which is a doxygen-compatible comment type so doxygen parses the comment. But doxygen throws a lot of warnings about the use of `#include` [within the comments](https://github.com/rurban/safeclib/blob/master/src/safeclib/memmove_s.c#L43). Doxygen warning: 

> C:/proj/jci_base_libs/Private/Libraries/C11AnnexK/safeclib/memmove_s.c:43: warning: explicit link request to 'include' could not be resolved

I haven't seen this issue before so I'm not exactly sure how it should be resolved other than completely removing that comment line so that the 'synopsis' is simply the function prototype. (at that point, why not just remove the SYNOPSIS and NAME sections because they duplicate the function definition immediately below?)

While we're at it, would there be any issue if we added [doxygen style tags](https://www.stack.nl/~dimitri/doxygen/manual/commands.html) like `@brief`, `@param`, `@return` to the function comment headers? The modified doxygen header comment for [`memmove_s`](https://github.com/rurban/safeclib/blob/master/src/safeclib/memmove_s.c#L38) would look like:

```
/**
 * @brief 
 *    The memmove_s function copies smax bytes from the region pointed to by 
 *    src into the region pointed to by dest. 
 * @details
 *    This copying takes place as if the smax bytes from the region pointed 
 *    to by src are ﬁrst copied into a temporary array of smax bytes that does 
 *    not overlap the region pointed to by dest or src, and then the smax 
 *    bytes from the temporary array are copied into the object region to by 
 *    dest.
 *
 * @remark SPECIFIED IN
 *    ISO/IEC TR 24731, Programming languages, environments
 *    and system software interfaces, Extensions to the C Library,
 *    Part I: Bounds-checking interfaces
 *
 * @param dest[out] pointer to the memory that will be replaced by src.
 * @param dmax   maximum length of the resulting dest, in bytes
 * @param src    pointer to the memory that will be copied to dest
 * @param smax   maximum number bytes of src that can be copied
 *
 * @pre   Neither dest nor src shall be a null pointer.
 * @pre   Neither dmax nor smax shall be 0.
 * @pre   dmax shall not be greater than RSIZE_MAX_MEM.
 * @pre   smax shall not be greater than dmax.
 *
 * @return
 *    EOK        successful operation
 *    ESNULLP    NULL pointer
 *    ESZEROL    zero length
 *    ESLEMAX    length exceeds max limit
 *    If there is a runtime-constraint violation, the memmove_s function
 *      stores zeros in the ﬁrst dmax characters of the region pointed to
 *      by dest if dest is not a null pointer and dmax is not greater
 *      than RSIZE_MAX_MEM.
 *
 * @relates
 *    memmove16_s(), memmove32_s(), memcpy_s(), memcpy16_s() memcpy32_s()
 *
 */
errno_t
memmove_s (void *dest, rsize_t dmax, const void *src, rsize_t smax)
{
   ...
}
```
so the doxygen html documentation would now look like:
![image](https://user-images.githubusercontent.com/8956541/29329736-76b92560-81bc-11e7-97d8-487cf8a6ca7a.png)

whereas originally the generated documentation without tags looked like:
![image](https://user-images.githubusercontent.com/8956541/29329700-558090c2-81bc-11e7-8574-2d6a3c377772.png)

**Comment by rurban** [comment]
Yes, of course. Looks much better.
Looks like they used some older pod-like doxygen.

**Comment by rurban** [comment]
Thanks. I published it at https://rurban.github.io/safeclib/
