### ISSUE TITLE
For strncpy_s and strncat_s slen==0 should be valid.

### ISSUE THREAD

**Issue by Juno-Explorer** [rurban/safeclib#31]
For strncpy_s() and strncat_s() standard doesn’t speak about what to do when slen=0!! it only says that slen shouldn’t be greater than RSIZE_MAX. 

I think slen = 0 should not be considered as runtime constraint violation and instead of ESZEROL we must return EOK and without modifying the destination buffer. I think strncat_s() misses this check.

**Comment by rurban** [comment]
That would need to follow the same logic as memcpy and friends, allowing slen=0 only with an C11 compiler, else erroring with ESZEROL.

**Comment by Juno-Explorer** [comment]
Yes

**Comment by rurban** [comment]
strncat_s was already ok, just the docs were wrong.

**Comment by rurban** [comment]
For consistency we should do this for all APIs with slen: 

src/extstr/strcasestr_s.c
src/extstr/strcpyfld_s.c
src/extstr/strcpyfldin_s.c
src/extstr/strcpyfldout_s.c
src/extstr/strcspn_s.c
src/extstr/strpbrk_s.c
src/extstr/strprefix_s.c
src/extstr/strspn_s.c
src/extstr/strstr_s.c
src/extwchar/wcslwr_s.c
src/extwchar/wcsnorm_s.c
src/extwchar/wcsstr_s.c
src/extwchar/wcsupr_s.c
~~src/str/strncat_s.c~~
~~src/str/strncpy_s.c~~
src/str/strtok_s.c
src/wchar/wcsncat_s.c
src/wchar/wcsncpy_s.c
src/wchar/wcstok_s.c
