### ISSUE TITLE
Move *cpy/move functions more towards C11/Windows

### ISSUE THREAD

**Issue by rurban** [rurban/safeclib#39]
The current implementation of C11 Annex K functions deviate a bit from the spec and the windows sec_api, the windows sec_api is a bit more relaxed with empty slen arguments than safeclib.

Get away with the #ifdef HAVE_C11 logic. See also issue #31 
Check all HAVE_C11 guards in the source and tests and make it the new default. This would make the library independent on using a C11 compiler for safeclib, and still follow the specs, but allow slen=0 shortcuts without failing.

In particular C11 sec_api allows empty slen to return immediately without dest check and cleaning.
Move that slen check upwards to mimic existing behavior.
The problem is with the footnote below *A zero return value implies ... that the result in s1 is null terminated.* With slen=0 alone it would not be guaranteed.

This would be the new slen check, the very first.
Following the specs, unlike windows sec_api:
```
    if (unlikely(slen == 0 && dest && dmax)) {
        *dest = '\0';
        return EOK;
    }
```
or variant 2, violating the spec footnote, following the windows sec_api.
```

    if (unlikely(slen == 0)) {
        if (dest && dmax)
            *dest = '\0';
        return EOK;
    }
```

e.g. the C11 standard says:

>> K.3.7.1.4 The strncpy_s function

Synopsis
```
#define __STDC_WANT_LIB_EXT1__ 1 
#include <string.h>
         errno_t strncpy_s(char * restrict s1,
              rsize_t s1max,
              const char * restrict s2,
              rsize_t n);
```
Runtime-constraints
* Neither s1 nor s2 shall be a null pointer. Neither s1max nor n shall be greater than RSIZE_MAX. s1max shall not equal zero. If n is not less than s1max, then s1max shall be greater than strnlen_s(s2, s1max). Copying shall not take place between objects that overlap.
* If there is a runtime-constraint violation, then if s1 is not a null pointer and s1max is greater than zero and not greater than RSIZE_MAX, then strncpy_s sets s1[0] to the null character.

Description
* The strncpy_s function copies not more than n successive characters (characters that follow a null character are not copied) from the array pointed to by s2 to the array pointed to by s1. If no null character was copied from s2, then s1[n] is set to a null character.

All elements following the terminating null character (if any) written by strncpy_s in the array of s1max characters pointed to by s1 take unspecified values when strncpy_s returns.

Returns
The strncpy_s function returns zero if there was no runtime-constraint violation. Otherwise, a nonzero value is returned. - A zero return value implies that all of the requested characters from the string pointed to by s2 fit within the array pointed to by s1 and that the result in s1 is null terminated.

ie. there's no ESZERO violation with n=0

Also with dmax > MAX clean dest, at least dest[0] or strlen(dest), not the whole overlarge dmax.

```
$ git grep 'slen == 0'
src/extstr/strcasestr_s.c:    if (unlikely(slen == 0)) {
src/extstr/strcpyfld_s.c:    if (unlikely(slen == 0)) {
src/extstr/strcpyfldin_s.c:    if (unlikely(slen == 0)) {
src/extstr/strcpyfldout_s.c:    if (unlikely(slen == 0)) {
src/extstr/strcspn_s.c:    if (unlikely(slen == 0 )) {
src/extstr/strpbrk_s.c:    if (unlikely(slen == 0 )) {
src/extstr/strspn_s.c:    if (unlikely(slen == 0 )) {
src/extstr/strstr_s.c:    if (unlikely(slen == 0)) {
src/extwchar/wcslwr_s.c:    if (unlikely(slen == 0)) {
src/extwchar/wcsstr_s.c:    if (unlikely(slen == 0)) {
src/extwchar/wcsupr_s.c:    if (unlikely(slen == 0)) {
src/str/strncat_s.c:            if (unlikely(slen == 0)) {
src/str/strncat_s.c:            if (unlikely(slen == 0)) {
src/str/strncpy_s.c:    if (unlikely(slen == 0)) {
src/str/strncpy_s.c:        if (unlikely(slen == 0)) {
src/str/strncpy_s.c:            if (unlikely(slen == 0)) {
src/str/strtok_s.c:            if (unlikely(slen == 0)) {
src/str/strtok_s.c:            if (unlikely(slen == 0)) {
src/wchar/wcsncat_s.c:            if (unlikely(slen == 0)) {
src/wchar/wcsncat_s.c:            if (unlikely(slen == 0)) {
src/wchar/wcsncpy_s.c:    if (unlikely(slen == 0)) {
src/wchar/wcsncpy_s.c:            if (unlikely(slen == 0)) {
src/wchar/wcsncpy_s.c:      if (unlikely(slen == 0)) {
src/wchar/wcstok_s.c:            if (unlikely(slen == 0)) {
src/wchar/wcstok_s.c:            if (unlikely(slen == 0)) {

$ git grep HAVE_C11 src
src/extmem/memccpy_s.c:#ifdef HAVE_C11
src/extmem/memcpy16_s.c:#ifdef HAVE_C11
src/extmem/memcpy32_s.c:#ifdef HAVE_C11
src/extmem/memmove16_s.c:#ifdef HAVE_C11
src/extmem/memmove32_s.c:#ifdef HAVE_C11
src/extmem/memset16_s.c:#ifdef HAVE_C11
src/extmem/memset32_s.c:#ifdef HAVE_C11
src/extstr/strcpyfld_s.c:#ifdef HAVE_C11
src/extstr/strcpyfldin_s.c:#ifdef HAVE_C11
src/extstr/strcpyfldout_s.c:#ifdef HAVE_C11
src/extwchar/wcslwr_s.c:#ifdef HAVE_C11
src/extwchar/wcsupr_s.c:#ifdef HAVE_C11
src/mem/memcpy_s.c:#ifdef HAVE_C11
src/mem/memmove_s.c:#ifdef HAVE_C11
src/mem/memset_s.c:#if defined HAVE_MEMSET_S && defined HAVE_C11 && defined WANT_C11
src/mem/memset_s.c:#ifdef HAVE_C11
```

**Comment by Juno-Explorer** [comment]
I think handle_error for dmax > RSIZE_MAX is not needed.

A/c to standard, 
If there is a runtime-constraint violation, then if s1 is not a null pointer and s1max is greater than zero and not greater than RSIZE_MAX, then strncpy_s sets s1[0] to the null character.

It clearly states that to set dest[0] = ‘\0’ dmax should be greater than 0 and less than RSIZE_MAX. So using handle_error for dmax > RSIZE_MAX is deviation from C11 Standard.

Moreover for slen = 0 standard doesn’t claim that it’s an error scenario (which I have already stated in issue#31) and other compilers which support C11 i.e IAR ARM and MSC doesn’t update destination at all when slen = 0. 

I think your changes to cater this issue would make your implementation to deviate from C11 standard.

**Comment by rurban** [comment]
I think you are right with clearing dest on dmax > MAX. I changed that in strncat_s, wcsncat_s with 19d4914cc7a1206 
but we do it with slen > MAX. Will revert that.

For the whole slen=0 scenario we'll be much more forgiving and do the HAVE_C11 logic. But interestingly on some cases dest is cleared, on some not. Still have to evaluate where, why and how.
