### ISSUE TITLE
Variance in name of parameters used in declaration & definition of functions

### ISSUE THREAD

**Issue by Juno-Explorer** [rurban/safeclib#4]
We were adding doxygen tags to SafeLib C file comments and came across variance in naming 
 of function parameters in function declaration & definition.

Please refer 
* mem_primitives_lib.h 
https://github.com/rurban/safeclib/blob/master/src/safeclib/mem_primitives_lib.h
*  mem_primitives_lib.c
https://github.com/rurban/safeclib/blob/master/src/safeclib/mem_primitives_lib.c

While we're at it, would there be any issue if we resolve the differences.

**Comment by rurban** [comment]
I don't see it yet, but go on

**Comment by rurban** [comment]
I see it now. I added a comment to PR #5 
In detail:
* len -> length: dislike, even if it's in newer libc manpages also.
* len -> dmax: I'm not sure yet. I'll play with it.

I caught one smax -> dmax mistake in memset_s.

**Comment by rurban** [comment]
I reverted some of those changes.
