### ISSUE TITLE
kernel module broken ?

### ISSUE THREAD

**Issue by ffontaine** [rurban/safeclib#41]
Hello,

I tried to build the kernel module but it seems broken:
- slkm_init.c includes ../safeclib/safeclib_private.h which is not found (this include should be replaced by safeclib_private.h and Kbuild should add -I$(src)/src in ccflags-y)
- even with this update, time.h (and wchar.h) are included in most of the header files but are not available in kernel space.

Best Regards,

Fabrice

**Comment by rurban** [comment]
Care for a patch? I'm just to busy with windows stuff right now.

**Comment by rurban** [comment]
I'm on it now. See the `gh41-kernel` branch
