### ISSUE TITLE
What is branch/tag strategy?

### ISSUE THREAD

**Issue by deserthacker** [rurban/safeclib#42]
Looks like there are a few tags and branches.

If I want to pull something down and build/install on Linux, is there a particular branch or tag I should be using?

Is there documentation, if not I'd be happy to update the README!

Thanks!

**Comment by rurban** [comment]
**master** is the stable development branch, and the branch which is worked on changes all the time. that time it was gh39-slen0.
**retpoline** needs to wait on gcc, 
**gh-pages** is the documentation branch for the website: https://rurban.github.io/safeclib/

There's no need to document these. It's selfdocumenting.
