### ISSUE TITLE
getting compilation error for test_vfwscanf_s.c

### ISSUE THREAD

**Issue by peiliu** [rurban/safeclib#44]
Hi, I'm getting a compilation error in test_vfwscanf_s.c.  Here is the error:

**test_vfwscanf_s.c: In function 'test_vfwscanf_s':
test_vfwscanf_s.c:70:10: error: incompatible type for argument 3 of 'vfwscanf_s'
     rc = vfwscanf_s(f, NULL, NULL);
          ^
In file included from test_vfwscanf_s.c:10:0:
../include/safe_str_lib.h:526:1: note: expected 'va_list' but argument is of type 'void *'
 vfwscanf_s(FILE *restrict stream,
 ^**

From my understanding, the 3rd argument accepts is 'va_list', and it can't be null.. thoughts?

**Comment by rurban** [comment]
Thanks, you are right

**Comment by peiliu** [comment]
I have built the code using rasberry pi 3. (gcc version 4.9.2 (Raspbian 4.9.2-10) )

Here is the GCC info:
pi@raspberrypi:~/git/safeclib $ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.9.2 (Raspbian 4.9.2-10)

**Comment by rurban** [comment]
Thanks, I added now arm-linux-gnueabihf to my cross toolchain smoker, and caught another bug there. See 33312d7907b92911ad3c2a0848662389b0bfb239
