### ISSUE TITLE
vsprintf_s() should return 0 for "vsprintf_s: len exceeds dmax"

### ISSUE THREAD

**Issue by Juno-Explorer** [rurban/safeclib#45]
**According to standard:**
 If no runtime-constraint violation occurred, the vsprintf_s function returns the number of characters written in the array, not counting the terminating null character. If an encoding error occurred, vsprintf_s returns a negative value. If any other runtime-constraint violation occurred, vsprintf_s returns zero. 

Scenario "vsprintf_s: len exceeds dmax" is **run-time constraint violation & not encoding error** so the return value should be 0.

Link to the code instance: https://github.com/rurban/safeclib/blob/master/src/str/vsprintf_s.c#L147

**Comment by rurban** [comment]
Yes, but in this case I think the standard made an error. I'll have to check the history of that.

**Comment by rurban** [comment]
Done with 345101c5404738b3d402f8f51cc505683ec8b28f and 76bfbf38961ffd498faed5faf59bda942cf22b37

When all other deviate from C11 and C11 is wrong so do we.
