### ISSUE TITLE
Why not to check runtime-constraints sort by priority?

### ISSUE THREAD

**Issue by chenlilong84** [rurban/safeclib#47]
Hi rurban,

According to your implementation, I wonder why not to check runtime-constraints sort by priority? Such as about strcpy_s, NULL pointer(ESNULLP) issue should be the highest priority,  because that will cause process crashes,  ESZEROL, ESLEMAX, ESOVRLP, or ESNOSPC should have lower priority, they just cause feature is not working.  What do you think?

strcpy_s (char * restrict dest, rsize_t dmax, const char * restrict src)
{
         .......
    if (unlikely(dest == NULL)) {
        .......
        return RCNEGATE(ESNULLP);
    }
    if (unlikely(dmax == 0)) {
        ........
        return RCNEGATE(ESZEROL);
    }
    if (**unlikely(dmax > RSIZE_MAX_STR)**) {
        .......
    }
    if (**unlikely(src == NULL)**) {
           ......
        return RCNEGATE(ESNULLP);
    }
     ........
}

**Comment by rurban** [comment]
We check mostly from left to right, in the very same order as the existing implementations. See the use_msvcrt checks in the tests, to return the very same error codes.
We never access invalid pointers anyway.
