### ISSUE TITLE
--disable-constraint-handler option

### ISSUE THREAD

**Issue by rurban** [rurban/safeclib#50]
#undef the run-time `invoke_safe_{str,mem}_constraint_handler` function calls in `safe_config.h`
to avoid the large strings, as in FreeBSD.

Most of the OS/libc folks complain about it, but it is useful, similar to their malloc hooks.  They are only used in the error cases.

**Comment by chenlilong84** [comment]
I think run-time constraint is a good point from design perspective, but it is 'chicken rib' on the large project, that will cause great  loss of performance.

**Comment by rurban** [comment]
It's no loss of performance, because they are only invoked in the very rare error cases.
The biggest win is in slimming down the cache-size. I"ll do benchmarks

**Comment by chenlilong84** [comment]
Yeah, I agreen with you, Indeed It is time to evalute performance lost after lots of check.
In additional, about runtime-constraint mechanism, I think it is similar with exception handle in the many OOP languages, also I have a good idea to use them reasonably via collecting exception log when runtime-constraint occurs, which is convient to do debug.

**Comment by rurban** [comment]
Benchmark results:

The size overhead for the constraint-handler is 35%-100%.
There is no measurable --disable-constraint-handler speedup, but a huge check _s slowdown of ~90%.
