### ISSUE TITLE
Improved C++ support

### ISSUE THREAD

**Issue by alexey-lysiuk** [rurban/safeclib#58]
First of all, thank you for supporting the great library.

I'm trying to use `safeclib` in C++11 code. My test case is very simple
```c++
#include <libsafec/safe_str_lib.h>

int main()
{
}
```

With GCC 5.4.0 there are lots of similar errors due to usage of `restrict` keyword
```
safe_compile.h:38:45: error: conflicting declaration ‘void* restrict’
                                       void *restrict       /* ptr */,
                                             ^
safe_compile.h:37:51: note: previous declaration as ‘const char* restrict’
 typedef void (*constraint_handler_t) (const char *restrict /* msg */,
                                                   ^
```
Adding `#define restrict __restrict` before inclusion of the header does the trick.
The solution, however, is far from being elegant. Probably this can be handled somehow during `configure`.

With Clang 4.0.1 there is an additional issue with errors like this
```
safe_str_lib.h:106:19: error: no matching literal operator for call to 'operator""_XSTR' with arguments of types 'const char *' and 'unsigned long', and no matching literal operator template
    BOS_CHK(dest) BOS_NULL(src);
                  ^
safe_compile.h:178:56: note: expanded from macro 'BOS_NULL'
    __attribute__((diagnose_if(_BOS_NULL(buf), "empty "_XSTR(buf), bos_chk_err)))
```
Apparently there should be space between string literal and `_XSTR()` macro. Otherwise C++11 compiler will treat a whole expression as user-defined literal.
This one can be solved by a simple search/replace but still it's worth mentioning I think.

**Comment by rurban** [comment]
Thanks, this is a regression. I believe the previous release handled C++ just fine. It was also in my smoked targets. I'll see what I can do. First it needs to be added to the smoke script.
