### ISSUE TITLE
sscanf_s not honoring size token for %s/%c

### ISSUE THREAD

**Issue by kellycouch** [rurban/safeclib#59]
Documentation notes that %s and %c must include both a pointer to buffer and a size of buffer as 2 parameters per token. However, the implementation appears to not handle this properly, and actually works the same as previous scanf, with just a pointer to buffer. If adding the size parameter, results in a crash.

**Comment by rurban** [comment]
Yes, that's not yet implemented. 

It will be huge vsscanf implementation (at least the size of the current library), and will open a can of worms. If there's a nice scanf MIT code, I'll take it. I only saw C++ code from Android bionic though. Maybe the FreeBSD variant.

We only do argument checks and pass it to the native vsscanf().

**Comment by rurban** [comment]
Might add a full implementation later, once I find one. 
The Huawei securec looks good, has the wrong License.
