### ISSUE TITLE
Strncpy_s segfaults by trying to memset a string literal to 0

### ISSUE THREAD

**Issue by inm01** [rurban/safeclib#72]
strncpy_s(dest, 32, "ShortString", 31); causes crash.

I realise this violates the precondition that says "dmax and slen should not be greater than the object sizes of dest and src", however, it would be nice if it were handled gracefully.
In _strncpy_s_chk we hit the case where slen > srcbos, taking us into handle_str_bos_overload(). The handle_error() function then tries to memset the src string to 0 which segfaults presumably because "ShortString" is in read-only data and can't we written to.  
I think the issue here is that dest and destbos should be passed into handle_str_bos_overload() rather than src and srcbos as this is what happens in _strncat_s_chk.

Regards.

**Comment by rurban** [comment]
Fixed with 3.5.1
