### ISSUE TITLE
64 bit version of memset_s does not set upper 4 bits of 64 bit word

### ISSUE THREAD

**Issue by inm01** [rurban/safeclib#73]
In the 64 bit version of mem_prim_set(), line 160 of mem_primitives_lib.c, value64 is created by copying the source byte multiple times to fill up the entire 64 bit word. However, there is a typo as the last bitshift operation should be 56 bits not 52. This results in the upper 4 bits being left unset and bits 52-59 potentially being incorrect. When value64 is then used in the while loop the error is duplicated on every pass.

**Comment by rurban** [comment]
Merged, thanks
