### ISSUE TITLE
Return value of malloc() not checked

### ISSUE THREAD

**Issue by hauke** [rurban/safeclib#78]
In this code it is assumed that malloc is successfully:
https://github.com/rurban/safeclib/blob/master/src/wchar/vswprintf_s.c#L185
I as far as I understood the manpage of vswprintf() it does not check for NULL.

We wanted to increase the RSIZE_MAX_WSTR to 2GB on our 32Bit system, but then would allocate 2GB here, which is too much.

**Comment by rurban** [comment]
Good catch!
