### ISSUE TITLE
safec3/libsafec3 compilation failed with gcc8.3.0, ARCH x86_64

### ISSUE THREAD

**Issue by rajasekha** [rurban/safeclib#79]
We are facing compilation issue with GCC8.3.0 from x86_64 arch.
Compilation : cross compilation
failed : libsafec3
Please let me who knows this solution ASAP.
make[6]: Entering directory `/local/reragamx/build_25092019/ugw_sw/openwrt/build_dir/target-x86_64_musl_lgm_he_cpe/libsafec3-03032018.0-g570fa5/tests'
  CCLD     p_memcpy_s
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: warning: -z retpolineplt ignored
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: warning: -z textonly ignored
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: perf_memcpy_s.o: in function `timing_loop':
perf_memcpy_s.c:(.text+0xa0): undefined reference to `__x86_indirect_thunk'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: perf_memcpy_s.c:(.text+0x14b): undefined reference to `__x86_indirect_thunk'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: perf_memcpy_s.c:(.text+0x1d3): undefined reference to `__x86_indirect_thunk'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: perf_memcpy_s.c:(.text+0x1f2): undefined reference to `__x86_return_thunk'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: perf_memcpy_s.o: in function `main':
perf_memcpy_s.c:(.text.startup+0x13): undefined reference to `__x86_indirect_thunk'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: perf_memcpy_s.c:(.text.startup+0x11d): undefined reference to `__x86_indirect_thunk'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: perf_memcpy_s.c:(.text.startup+0x134): undefined reference to `__x86_indirect_thunk'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: perf_memcpy_s.c:(.text.startup+0x240): undefined reference to `__x86_indirect_thunk'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: perf_memcpy_s.c:(.text.startup+0x257): undefined reference to `__x86_indirect_thunk'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: perf_memcpy_s.o:perf_memcpy_s.c:(.text.startup+0x35d): more undefined references to `__x86_indirect_thunk' follow
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: perf_memcpy_s.o: in function `main':
perf_memcpy_s.c:(.text.startup+0x36e): undefined reference to `__x86_return_thunk'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: ../src/.libs/libsafec-3.3.so: undefined reference to `__x86_indirect_thunk_rbp'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: ../src/.libs/libsafec-3.3.so: undefined reference to `__x86_indirect_thunk_rax'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: ../src/.libs/libsafec-3.3.so: undefined reference to `__x86_indirect_thunk_rdx'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: ../src/.libs/libsafec-3.3.so: undefined reference to `__x86_indirect_thunk_r14'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: ../src/.libs/libsafec-3.3.so: undefined reference to `__x86_indirect_thunk_rbx'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: ../src/.libs/libsafec-3.3.so: undefined reference to `__x86_indirect_thunk_r10'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: ../src/.libs/libsafec-3.3.so: undefined reference to `__x86_indirect_thunk_rcx'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: ../src/.libs/libsafec-3.3.so: undefined reference to `__x86_indirect_thunk_r12'
/local/reragamx/build_25092019/ugw_sw/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: ../src/.libs/libsafec-3.3.so: undefined reference to `__x86_indirect_thunk_r8'
collect2: error: ld returned 1 exit status
make[6]: *** [p_memcpy_s] Error 1
make[6]: Leaving directory `/local/reragamx/build_25092019/ugw_sw/openwrt/build_dir/target-x86_64_musl_lgm_he_cpe/libsafec3-03032018.0-g570fa5/tests'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory `/local/reragamx/build_25092019/ugw_sw/openwrt/build_dir/target-x86_64_musl_lgm_he_cpe/libsafec3-03032018.0-g570fa5'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/local/reragamx/build_25092019/ugw_sw/openwrt/build_dir/target-x86_64_musl_lgm_he_cpe/libsafec3-03032018.0-g570fa5'
make[3]: *** [/local/reragamx/build_25092019/ugw_sw/openwrt/build_dir/target-x86_64_musl_lgm_he_cpe/libsafec3-03032018.0-g570fa5/.built] Error 2
make[3]: Leaving directory `/local/reragamx/build_25092019/ugw_sw/feeds/opensource/safec3'
time: package/feeds/opensource/safec3/compile#0.23#0.25#0.46
make[2]: *** [package/feeds/opensource/safec3/compile] Error 2

**Comment by rurban** [comment]
No ideas about this error. libsafec-3.3 is pretty old, and I never heard of these __x86_indirect_thunk errors. Looks like a toolchain issue (binutils? linker?) to me.

**Comment by rurban** [comment]
Stalled
