### ISSUE TITLE
tests fail on big endian

### ISSUE THREAD

**Issue by kilobyte** [rurban/safeclib#81]
The testsuite fails on all big-endian architectures.

On 32-bit BE (powerpc, hppa):
```
t_memmove32_s
```

On 64-bit BE (s390x, ppc64, sparc64):
```
t_memset_s
t_sscanf_s
t_swscanf_s
t_fwscanf_s
t_vfwscanf_s
t_vswscanf_s
t_vwscanf_s
t_wscanf_s
t_memmove32_s
```
(except for `t_memset_s` on s390x, which passes).

**Comment by rurban** [comment]
Do you know if this a regression? Did it work before? I'll need some time to setup a test machine, hope qemu can find it.

**Comment by kilobyte** [comment]
I've never tried an earlier version.

**Comment by rurban** [comment]
Thanks, good to know

**Comment by rurban** [comment]
BTW: This is only a testsuite issue, not a library problem.
big-endian archs are not supported anymore on fedora/redhat/debian, so it's hard to adjust the testsuite. Please ignore those failures

**Comment by kilobyte** [comment]
All of these three support at least s390x officially, and eg. Debian has powerpc ppc64 sparc64 hppa m68k as second-class ports.

**Comment by rurban** [comment]
Good. I'm just preparing the Fedora rpm. So I can hope I can test this at least on the debian build machines soon, when preparing the deb's.

**Comment by rurban** [comment]
Started adding multi-arch CI: 
Some on travis via docker and qemu, the two arm's via drone.io https://cloud.drone.io/rurban/safeclib

**Comment by rurban** [comment]
I can reproduce some of the errors, but they appear to be ubuntu-only related. I'm not able to reproduce or debug them locally, via fedora or debian cross + qemu nor via docker.
I don't have ubuntu as I favor proper distros, not do i know how to detect ubuntu easily to skip those tests. 
So could only add docs to the failing testcases.

See e.g. https://travis-ci.org/github/rurban/safeclib/builds/722639560

t_memcmp16_s:
 * fails: ubuntu-aarch64-linux-native and aarch64-fedora-docker,
 * but passes {debian,centos,fedora}-aarch64-linux

t_localtime_s, t_gmtime_s:
 * fails: ubuntu-arm32-linux{,-qemu} (arm32v7), ubuntu-s390x-linux-qemu
 * but passes: debian-arm32-linux, {debian,fedoar}-s390x-linux
