### ISSUE TITLE
Force HAVE_VSNPRINTF_S to 0

### ISSUE THREAD

**Issue by Yrchgrchh** [rurban/safeclib#87]
Hi,

Is there a way to force HAVE_VSNPRINTF_S macro to be undefined, so that _vsnprintf_s_chk is built and used all the time?

I tried playing with CFLAGS, but seems like configure ignores them.

**Comment by rurban** [comment]
This is defined in config.h, so adding -UHAVE_VSNPRINTF_S to CFLAGS or DEFS should work.
configure creates this definition, so it ignores it of course.
make is where add this override.
Or just edit `config.h`
