### ISSUE TITLE
Include file doesn't know type 'size_t'

### ISSUE THREAD

**Issue by cybessk0011** [rurban/safeclib#89]
I am writing a simple program to verify my install went correctly on Debian 10, and when I include the safe_str_lib.h header and link the library I get an `error: unknown type name 'size_t'`. Below I have included my code and error respectively, and I thank you for any help you are able to provide.
![image](https://user-images.githubusercontent.com/57372095/81842495-190a1180-951a-11ea-9989-f9de95cfd0b9.png)
![image](https://user-images.githubusercontent.com/57372095/81842561-35a64980-951a-11ea-9f05-68e8b5a544ba.png)

**Comment by rurban** [comment]
C99 is required. But we might add one if the defining headers internally. See https://en.cppreference.com/w/c/types/size_t

Like stddef.h or stdlib.h

**Comment by cybessk0011** [comment]
Yes I am using Debian x86_64. This problem seems to go away when I include the direct file path instead of linking to it while compiling. The problem I recieve after that is an `undefined reference to '_strcyp_s_chk'`. Any idea why the macro would be giving me issues?

**Comment by rurban** [comment]
That looks like a typo. Really _strcyp_s_chk

**Comment by cybessk0011** [comment]
My apologies, I meant to type _strcpy_s_chk.

**Comment by rurban** [comment]
Besides the wrong compilation cmd:
`gcc -I/usr/local/include/libsafec test-gh89.c -lsafec-3.6.0`

I moved the offending typedef size_t below  the definitions for size_t.
Thanks.

**Comment by rurban** [comment]
Fixed wit5da8464c092b2f234442824d3dbb49343e58bb16h , thanks
