### ISSUE TITLE
Question:  What is the relationship between this safeclib and https://github.com/intel/safestringlib ??

### ISSUE THREAD

**Issue by dxjones** [rurban/safeclib#90]
We have been using "safeclib v08112019 3.5.1" for a large software project.  Someone recently pointed out the existence of https://github.com/intel/safestringlib with the suggestion that "Intel has extended safeclib" and it "might be a better option for us".  I am skeptical, but I have no concrete information to decide either way.

Can you please clarify what the relationship is between "safeclib 3.5.1" and the Intel "safestringlib" repo?

Are they parallel forks?  Are they compatible / incompatible with each other?  Is one of them more up-to-date than the other?  Are there different features/functions?

Any guidance would be appreciated.

**Comment by rurban** [comment]
This is the original fork from an old sourceforge project by Cisco.
Intel forked it also but is years behind. Compare the features.
This is one complete, Intel's is ASCII only, and not really maintained.

**Comment by dxjones** [comment]
Thanks for the clear answer.  We'll keep using safeclib for our project.
