### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by mohd-akram** [rurban/safeclib#91]
I just came across this library and the versioning scheme seems very confusing. The library files have a version suffix which means it's difficult to simply do `-lsafec`. The pkg-config file has a completely different version (eg. `02092020.0-g6d921f`) which basically can't really be queried. Lastly, the library uses a different name in the repo vs in the generated tarballs. I propose:

- One single semantic version continued from the current `3.6.0`
- Produce unversioned library files - if someone requires a specific version they can use `pkg-config` to check. Furthermore, the shared library already has version info.
- Rename the tarballs from `libsafec` to `safeclib` to match the project's name.

Semantic versioning will allow easy querying via `pkg-config` at build time, and built-in version info in the shared library will handle runtime behavior. This matches standard practice and will make the library much easier to use, reducing the barrier to safe coding.

**Comment by rurban** [comment]
I agree with you. But unfortunately this odd scheme was already in place when I took it over.

It's really tempting to replace it with normal names and versions, but more importantly I don't really want to impact build systems.

**Comment by mohd-akram** [comment]
Given the current state, I don't think this will really break anything. If someone was using pkg-config, they couldn't have been doing a greater-than or less-than check because the current pkgconfig version isn't sortable - so if they were checking for a version it would be an exact match, which would break anyway with every new version. As for the library filename, the same thing applies - every new version is already a breaking change because the filename changes. And lastly, the only folks who probably care about the tarball name is package maintainers (me), and they would simply have to update it once there's a new version - previously uploaded tarballs are unaffected. So really, I think a new version `3.7.0` with the mentioned changes should be fine.

**Comment by rurban** [comment]
Thanks for your input as package maintainer. This is probably the most important opinion. 

I'll come back with questions later. First I want to finish the new strings library, u8. Strings really need to be UTF-8, nothing else. This will be 3.7

**Comment by kloczek** [comment]
@rurban
It is not only about library but package tagging as well.
Currently is used `v<day><month><year>`
Please at least change that to `v<year><month><day>`. Using that pattern does not make new version greater than previous one.

Latest dist tar ball is even worse as it contains as version string `02092020.0-g6d921f`.
First of all `-` is not accepted by any package manager.
Second is that this is why any VCS is using tags to not use commit number/commit hash.

Nothing in whole source tree except note in Changelog in for example https://github.com/rurban/safeclib/releases/download/v02092020/libsafec-02092020.tar.xz says that is this is version 3.6.
My understanding is that current tagging/versioning convention is used for some automation.
If that is true please at lease add secondary tags like `3.6` to allow download autogenerated from git tab tar balls using real version string.

Looks like safeclib is only git based project which is using that strange convention and it makes only some difficulty on packaging and/or automatic detection new versions

Package name as well is a bit confusing. For example latest dist tar balls are names as libsafec-02092020.tar.xz and git module name is `safeclib`.

At lease add some side tags with version string mentioned in Changelog file would be really welcome (especially if you don't have some plans to make new release soon).

**Comment by rurban** [comment]
Yes, I agree on all points. The only excuse I have is that I've inherited that mess from cisco.

I've decided to use proper semantic versioning beginning with the next release. I'll keep the date tag in git optionally, but nowhere else.

**Comment by mohd-akram** [comment]
Is there any update on this? Thanks.

**Comment by rurban** [comment]
Got work to do on other libs, and the u8 feature got sidelined. 
the next release will change to semantic versioning. it's already in the semver branch

**Comment by DBJDBJ** [comment]
" .. The only excuse I have is that I've inherited that mess from cisco...." 😆

**Comment by rurban** [comment]
Some testing needed still, I think

**Comment by rurban** [comment]
Merged into master, release 3.7.0 soon
