### ISSUE TITLE
don't try to install wcsnaticmp_s.3 man page if configured with  --disable-wchar

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [rurban/safeclib#95]
I've configured it with `--disable-wchar` and the build fails at
`/usr/bin/install: cannot stat './doc/man/man3/wcsnaticmp_s.3': No such file or directory`

**Comment by telans** [comment]
`--disable-doc` fails with `rm: cannot remove 'doc/man': No such file or directory`
