### ISSUE TITLE
kernel safe_lib.h:145:61: error: unknown type name ‘time_t’

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [rurban/safeclib#96]
I'm trying to build the kernel module on gentoo and I get this:
`safe_lib.h:145:61: error: unknown type name ‘time_t’`

which header is missing?

complete log here
https://gist.github.com/126c1648c848257693b888aab9687d28

**Comment by rurban** [comment]
Yes, time_t was recently changed to support 64bit. This needs a patch

**Comment by rurban** [comment]
Can you check your gentoo 5.10 time_t definition?
The current logic is:
```
/* Needed since the switch to time64_t */
#if defined CONFIG_COMPAT_32BIT_TIME && defined _LINUX_TIME64_H && defined __VDSO_TIME32_H
#define time_t old_time32_t
#endif
```
And see https://www.gnu.org/software/libc/manual/html_node/64_002dbit-time-symbol-handling.html
I only have a 5.9 kernel (fedora), and there we have a proper dual-time support.

**Comment by rurban** [comment]
Does this help?

```diff
--- src/safeclib_private.h
+++ src/safeclib_private.h
@@ -52,6 +52,8 @@
 /* Needed since the switch to time64_t */
 #if defined CONFIG_COMPAT_32BIT_TIME && defined _LINUX_TIME64_H && defined __VDSO_TIME32_H
 #define time_t old_time32_t
+#elif defined _LINUX_TIME64_H && !defined __VDSO_TIME32_H
+#define time_t time64_t
 #endif
 
 #define RCNEGATE(x) (-(x))
```

**Comment by Alessandro-Barbieri** [comment]
The patch didn't worked for me. I've enabled `COMPAT_32TIME` in the kernel and it worked

**Comment by rurban** [comment]
Bad. Hopefully someone else can fix this later.
