### ISSUE TITLE
sprintf_s doesn't handle empty string correctly

### ISSUE THREAD

**Issue by cliffwy** [rurban/safeclib#97]
call this function:    sprintf_s(buff, sizeof(buff), "%s", "");
it gives error. because the call to "vsnprintf" returns 0. which is correct because it's printing empty string.  
```
if (unlikely(ret <= 0)) {
        char errstr[128] = "sprintf_s: ";
        strcat(errstr, strerror(errno));
        handle_error(dest, dmax, errstr, -ret);
    }
```

**Comment by DBJDBJ** [comment]
The whole of ISO C does not handle the empty string. Correctly or not. 

```
strlen("") == 0

""[0] == '\0' 
```

But then a lot of people have the same problem, thus stepping on others' toes. [An example](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/strings/nothing-and-strings), from a different galaxy, but on the same subject.

Live with it&trade;            

:wink:

**Comment by rurban** [comment]
The _s extension defines what to do with an empty string and NULL, which I'm going to implement properly in the printf branch.
There were too many edge-cases not handled correctly.
