### ISSUE TITLE
add/fix probe for -fstack-protector-strong -fstack-clash-protection

### ISSUE THREAD

**Issue by Yatheesha1** [rurban/safeclib#98]
I tried to configure in Mac m1, I am getting following error

/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
  CC       mem/safe_mem_constraint.lo
clang: error: argument unused during compilation: '-fstack-clash-protection' [-Werror,-Wunused-command-line-argument]
make[2]: *** [mem/safe_mem_constraint.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by rurban** [comment]
Howe I can detect the M1?

**Comment by Yatheesha1** [comment]
> How can I detect the M1?
> autoconf AX_APPEND_COMPILE_FLAGS probes the compiler if `-fstack-clash-protection` is usable.
> 
> See run-aarch64.sh where I had to disable it

Its MacBook with silicon chip(M1-arm64)

**Comment by false** [comment]
Same issue happens on macOS Big Sur 11.5.1 x86_64 (so it seems it is not related to the M1 arch only).

`sed -i '' -e 's,-fstack-protector-strong -fstack-clash-protection,,' Makefile */Makefile`

fixes it

**Comment by Yatheesha1** [comment]
> sed -i '' -e 's,-fstack-protector-strong -fstack-clash-protection,,' Makefile */Makefile

This is triggering new euro

user@pc Safeclib % make                                                                                    
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
  CC       mem/memset_s.lo
mem/memset_s.c:132:5: error: too few operands for instruction
    MEMORY_BARRIER;
    ^
./mem/mem_primitives_lib.h:147:37: note: expanded from macro 'MEMORY_BARRIER'
#define MEMORY_BARRIER ASM_VOLATILE("dmb; dsb; isb" ::: "memory")
                                    ^
<inline asm>:1:2: note: instantiated into assembly here
        dmb; dsb; isb
        ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [mem/memset_s.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by rurban** [comment]
I fixed the wrong dmb instruction. The manual states that the dmb option (ie ish) is optional, but apparently is not. So I added it for aarch64 (which includes the m1)

**Comment by Yatheesha1** [comment]
Yes, now its compiled, thank you

**Comment by rurban** [comment]
I still have no idea why certain compilers pass the probe but throw run-time errors.
But now we have --disable-hardening to work around that.
