### ISSUE TITLE
Must they be macros?

### ISSUE THREAD

**Issue by ulatekh** [rurban/safeclib#99]
I'm porting a large amount of Windows code to Linux, and so I needed a safe-C-lib implementation.

The issue is that functions such as vsprintf_s() (the first one I ran into) are defined as macros.
This makes it impossible to define the templated C++ version that Windows and MinGW offer.
e.g. `template<size_t S> int vsprintf_s(char (&dest)[S], char const *format, va_list args) { return vsprintf_s(dest, S, format, args); }`
But since vsprintf_s() is defined as a macro in safe_str_lib.h, I can't write this templated version.

**Comment by Th3T3chn0G1t** [comment]
Have you tried `undef`ing `vsprintf_s`? It looks like the templated version is an extension by the MS CRT.

**Comment by rurban** [comment]
Yes, they must be macros to enable the FORTIFY_SOURCE tricks, to do compile-time bounds checking.

Just use the _chk functions instead for your templates, and undefine the original _s function.
With macros everything is easier, just autoconf probing is different.

**Comment by ulatekh** [comment]
By the time you replied to this, I had already ported our source-code base to conform to safeclib's API.
I have a lot of inline `#ifndef _MSC_VER ... #endif // !_MSC_VER` blocks to add the necessary size parameters.
(Except for `snprintf_s()`, which is called `_snprintf_s()` in MS Windows, so that was an `#ifdef _WIN32` test.)
No problem; it's all good.
